version: '3.8'

services:
  db:
    image: postgres:15
    container_name: employee_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d employee_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: employee_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/employee_db
      MAX_PHOTO_SIZE_KB: 200

    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads_data:/app/app/static/uploads
    restart: unless-stopped

volumes:
  postgres_data:
  uploads_data: